AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "clubes-api-go\nSample SAM Template for clubes-api-go\n# parameter\u540D\
  \u306F\u30A2\u30F3\u30C0\u30FC\u30B9\u30B3\u30A2\u4F7F\u3048\u306A\u3044\uFF08\u307D\
  \u3044\uFF09\n"
Parameters:
  AwsAccessKey:
    Type: String
  AwsSecretAccessKey:
    Type: String
  ConsumerKey:
    Type: String
  ConsumerSecret:
    Type: String
  AccessToken:
    Type: String
  AccessTokenSecret:
    Type: String
Globals:
  Function:
    Timeout: 5
  Api:
    Cors:
      AllowMethods: '''DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'''
      AllowHeaders: '''Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'''
      AllowOrigin: '''*'''
Resources:
  GetTweetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://clubes-api-go/bbaea30c8b83fc41dab222387e6360e3
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /tweets
            Method: GET
      Environment:
        Variables:
          AWS_ACCEESS_KEY:
            Ref: AwsAccessKey
          AWS_SECRET_ACCEESS_KEY:
            Ref: AwsSecretAccessKey
          CONSUMER_KEY:
            Ref: ConsumerKey
          CONSUMER_SECRET:
            Ref: ConsumerSecret
          ACCESS_TOKEN:
            Ref: AccessToken
          ACCESS_TOKEN_SECRET:
            Ref: AccessTokenSecret
  SearchTweetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://clubes-api-go/4930f30c99efe46eec7e87b4a4039c29
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /tweets/search
            Method: GET
      Environment:
        Variables:
          AWS_ACCEESS_KEY:
            Ref: AwsAccessKey
          AWS_SECRET_ACCEESS_KEY:
            Ref: AwsSecretAccessKey
          CONSUMER_KEY:
            Ref: ConsumerKey
          CONSUMER_SECRET:
            Ref: ConsumerSecret
          ACCESS_TOKEN:
            Ref: AccessToken
          ACCESS_TOKEN_SECRET:
            Ref: AccessTokenSecret
Outputs:
  TweetAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  GetTweetFunction:
    Description: First Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTweetFunction
      - Arn
  GetTweetFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - GetTweetFunctionRole
      - Arn
  SearchTweetFunction:
    Description: First Lambda Function ARN
    Value:
      Fn::GetAtt:
      - SearchTweetFunction
      - Arn
  SearchTweetFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - SearchTweetFunctionRole
      - Arn
